version: "3"

services:
  http:
    image: php:8.1-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app

  composer:
    image: composer/composer
    command: composer install
    volumes:
      - ./:/app
