version: "3"

services:
  http:
     image: php:8.1-apache
     ports:
       - "88:80"
     volumes:
       - .:/var/www/html

#  composer:
#    image: composer/composer
#    command: composer install
#    volumes:
#      - ./:/app
